<Coord> ::= <S> <I> . <I> , <S> <I> . <I> | <I> . <I> , <S> <I> . <I> | <S> <I> . <I> , <I> . <I> |  <I> . <I> , <I> . <I>
<I> ::= [1-9] <S> | 0 <P> | [0-9]
<P> ::= 0 <P> | 0
<S> ::= [0-9] <S> | [0-9]
<S> ::= \+ | -





